<?php

namespace ContainerWvXo1vK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_EZN9CeQService extends App_KernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.EZN9CeQ' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Messages/BoothNotificationHandler.php';

        return $container->privates['.messenger.handler_descriptor.EZN9CeQ'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Messages\BoothNotificationHandler(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Services\\Webdav'] ?? $container->load('getWebdavService'))), []);
    }
}
