<?php

namespace ContainerWvXo1vK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TQnptkYService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.TQnptkY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TQnptkY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'convert' => ['privates', 'App\\Services\\Base64Convert', 'getBase64ConvertService', true],
            'dav' => ['privates', 'App\\Services\\Webdav', 'getWebdavService', true],
            'lotRepo' => ['privates', 'App\\Repository\\LotDataRepository', 'getLotDataRepositoryService', true],
            'poRepo' => ['privates', 'App\\Repository\\PoRepository', 'getPoRepositoryService', true],
        ], [
            'convert' => 'App\\Services\\Base64Convert',
            'dav' => 'App\\Services\\Webdav',
            'lotRepo' => 'App\\Repository\\LotDataRepository',
            'poRepo' => 'App\\Repository\\PoRepository',
        ]);
    }
}
