<?php

namespace ContainerWvXo1vK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__R6xlctService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator..R6xlct' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..R6xlct'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'LotsRepo' => ['privates', 'App\\Repository\\LotDataRepository', 'getLotDataRepositoryService', true],
            'csv' => ['privates', 'App\\Services\\CreateCSV', 'getCreateCSVService', true],
            'emailsRepo' => ['privates', 'App\\Repository\\EmailsForDataRepository', 'getEmailsForDataRepositoryService', true],
            'mailer' => ['privates', 'App\\Services\\SendMail', 'getSendMailService', true],
        ], [
            'LotsRepo' => 'App\\Repository\\LotDataRepository',
            'csv' => 'App\\Services\\CreateCSV',
            'emailsRepo' => 'App\\Repository\\EmailsForDataRepository',
            'mailer' => 'App\\Services\\SendMail',
        ]);
    }
}
