<?php

namespace ContainerWvXo1vK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QSiPVOkService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.QSiPVOk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QSiPVOk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'config' => ['privates', '.errored..service_locator.QSiPVOk.App\\Entity\\Configuration', NULL, 'Cannot autowire service ".service_locator.QSiPVOk": it references class "App\\Entity\\Configuration" but no such service exists.'],
        ], [
            'config' => 'App\\Entity\\Configuration',
        ]);
    }
}
