<?php

namespace ContainerWvXo1vK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZL5Ntz5Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.zL5Ntz5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zL5Ntz5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dav' => ['privates', 'App\\Services\\Webdav', 'getWebdavService', true],
        ], [
            'dav' => 'App\\Services\\Webdav',
        ]);
    }
}
