<?php

namespace ContainerWvXo1vK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GJu2fT6Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.GJu2fT6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GJu2fT6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'BoxRepo' => ['privates', 'App\\Repository\\BoxSizePresetsRepository', 'getBoxSizePresetsRepositoryService', true],
            'ConfigurationRepo' => ['privates', 'App\\Repository\\ConfigurationRepository', 'getConfigurationRepositoryService', true],
            'EmailsRepo' => ['privates', 'App\\Repository\\EmailsForDataRepository', 'getEmailsForDataRepositoryService', true],
            'repo' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'BoxRepo' => 'App\\Repository\\BoxSizePresetsRepository',
            'ConfigurationRepo' => 'App\\Repository\\ConfigurationRepository',
            'EmailsRepo' => 'App\\Repository\\EmailsForDataRepository',
            'repo' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
