<?php

namespace ContainerWvXo1vK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailsForDataService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.yl9MWu0.App\Entity\EmailsForData' shared service.
     *
     * @return \App\Entity\EmailsForData
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.yl9MWu0": it references class "App\\Entity\\EmailsForData" but no such service exists.');
    }
}
