<?php

namespace ContainerWvXo1vK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUploadFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\UploadFormType' shared autowired service.
     *
     * @return \App\Form\UploadFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/UploadFormType.php';

        return $container->privates['App\\Form\\UploadFormType'] = new \App\Form\UploadFormType();
    }
}
