<?php

namespace ContainerWvXo1vK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebdavControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\WebdavController' shared autowired service.
     *
     * @return \App\Controller\WebdavController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/WebdavController.php';

        $container->services['App\\Controller\\WebdavController'] = $instance = new \App\Controller\WebdavController();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\WebdavController', $container));

        return $instance;
    }
}
