<?php

namespace ContainerZvMUppj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VqwTAD6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vqwTAD6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vqwTAD6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'BoxRepo' => ['privates', 'App\\Repository\\BoxSizePresetsRepository', 'getBoxSizePresetsRepositoryService', true],
            'ConfigurationRepo' => ['privates', 'App\\Repository\\ConfigurationRepository', 'getConfigurationRepositoryService', true],
            'EmailsRepo' => ['privates', 'App\\Repository\\EmailsForDataRepository', 'getEmailsForDataRepositoryService', true],
            'UserRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'BoxRepo' => 'App\\Repository\\BoxSizePresetsRepository',
            'ConfigurationRepo' => 'App\\Repository\\ConfigurationRepository',
            'EmailsRepo' => 'App\\Repository\\EmailsForDataRepository',
            'UserRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
