<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container33RXflc\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container33RXflc/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container33RXflc.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container33RXflc\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container33RXflc\App_KernelProdContainer([
    'container.build_hash' => '33RXflc',
    'container.build_id' => '5a89c18f',
    'container.build_time' => 1616514262,
], __DIR__.\DIRECTORY_SEPARATOR.'Container33RXflc');
