<?php

namespace ContainerOIi4zyU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BndMRO9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bndMRO9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bndMRO9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'PoRepository' => ['privates', 'App\\Repository\\PoRepository', 'getPoRepositoryService', true],
            'convert' => ['privates', 'App\\Services\\Base64Convert', 'getBase64ConvertService', true],
            'dav' => ['privates', 'App\\Services\\Webdav', 'getWebdavService', true],
            'lotRepo' => ['privates', 'App\\Repository\\LotRepository', 'getLotRepositoryService', true],
        ], [
            'PoRepository' => 'App\\Repository\\PoRepository',
            'convert' => 'App\\Services\\Base64Convert',
            'dav' => 'App\\Services\\Webdav',
            'lotRepo' => 'App\\Repository\\LotRepository',
        ]);
    }
}
