<?php

namespace ContainerOIi4zyU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NQFJRwOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NQFJRwO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NQFJRwO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'LotRepo' => ['privates', 'App\\Repository\\LotRepository', 'getLotRepositoryService', true],
            'dav' => ['privates', 'App\\Services\\Webdav', 'getWebdavService', true],
        ], [
            'LotRepo' => 'App\\Repository\\LotRepository',
            'dav' => 'App\\Services\\Webdav',
        ]);
    }
}
