<?php

namespace ContainerOIi4zyU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigurationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QSiPVOk.App\Entity\Configuration' shared service.
     *
     * @return \App\Entity\Configuration
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.QSiPVOk": it references class "App\\Entity\\Configuration" but no such service exists.');
    }
}
