<?php

namespace ContainerOIi4zyU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigurationTypeFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ConfigurationTypeFormType' shared autowired service.
     *
     * @return \App\Form\ConfigurationTypeFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ConfigurationTypeFormType.php';

        return $container->privates['App\\Form\\ConfigurationTypeFormType'] = new \App\Form\ConfigurationTypeFormType();
    }
}
