<?php

namespace ContainerOIi4zyU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebdavService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\Webdav' shared autowired service.
     *
     * @return \App\Services\Webdav
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Webdav.php';

        return $container->privates['App\\Services\\Webdav'] = new \App\Services\Webdav(($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))));
    }
}
