<?php

namespace ContainerYfkQCc1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XO2ZHqKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XO2ZHqK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XO2ZHqK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'LotRepo' => ['privates', 'App\\Repository\\LotRepository', 'getLotRepositoryService', true],
        ], [
            'LotRepo' => 'App\\Repository\\LotRepository',
        ]);
    }
}
