<?php

namespace ContainerYfkQCc1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yl9MWu0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yl9MWu0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yl9MWu0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'EmailsForData' => ['privates', '.errored..service_locator.yl9MWu0.App\\Entity\\EmailsForData', NULL, 'Cannot autowire service ".service_locator.yl9MWu0": it references class "App\\Entity\\EmailsForData" but no such service exists.'],
        ], [
            'EmailsForData' => 'App\\Entity\\EmailsForData',
        ]);
    }
}
