<?php

namespace ContainerYfkQCc1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBoxSizePresetsFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\BoxSizePresetsFormType' shared autowired service.
     *
     * @return \App\Form\BoxSizePresetsFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/BoxSizePresetsFormType.php';

        return $container->privates['App\\Form\\BoxSizePresetsFormType'] = new \App\Form\BoxSizePresetsFormType();
    }
}
