<?php

namespace ContainerYfkQCc1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBoxSizePresetsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hiuod1Z.App\Entity\BoxSizePresets' shared service.
     *
     * @return \App\Entity\BoxSizePresets
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.hiuod1Z": it references class "App\\Entity\\BoxSizePresets" but no such service exists.');
    }
}
