<?php

namespace Container33RXflc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hiuod1ZService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.hiuod1Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hiuod1Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'BoxPresets' => ['privates', '.errored..service_locator.hiuod1Z.App\\Entity\\BoxSizePresets', NULL, 'Cannot autowire service ".service_locator.hiuod1Z": it references class "App\\Entity\\BoxSizePresets" but no such service exists.'],
        ], [
            'BoxPresets' => 'App\\Entity\\BoxSizePresets',
        ]);
    }
}
