<?php

namespace Container33RXflc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModifyUserFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ModifyUserFormType' shared autowired service.
     *
     * @return \App\Form\ModifyUserFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ModifyUserFormType.php';

        return $container->privates['App\\Form\\ModifyUserFormType'] = new \App\Form\ModifyUserFormType();
    }
}
