<?php

namespace Container9Oxdllt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N45nOfEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n45nOfE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n45nOfE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'LotsRepo' => ['privates', 'App\\Repository\\LotRepository', 'getLotRepositoryService', true],
            'csv' => ['privates', 'App\\Services\\CreateCSV', 'getCreateCSVService', true],
        ], [
            'LotsRepo' => 'App\\Repository\\LotRepository',
            'csv' => 'App\\Services\\CreateCSV',
        ]);
    }
}
