<?php

namespace Container9Oxdllt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SFNCuTQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sFNCuTQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sFNCuTQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\AdminController::deletePhoto' => ['privates', '.service_locator.NQFJRwO', 'get_ServiceLocator_NQFJRwOService', true],
            'App\\Controller\\Admin\\AdminController::getCsv' => ['privates', '.service_locator.n45nOfE', 'get_ServiceLocator_N45nOfEService', true],
            'App\\Controller\\Admin\\AdminController::mailCsv' => ['privates', '.service_locator.6M8Db7T', 'get_ServiceLocator_6M8Db7TService', true],
            'App\\Controller\\Admin\\AdminController::markAsDone' => ['privates', '.service_locator.9jx6pm9', 'get_ServiceLocator_9jx6pm9Service', true],
            'App\\Controller\\Admin\\AdminController::polist' => ['privates', '.service_locator.1AXQdDL', 'get_ServiceLocator_1AXQdDLService', true],
            'App\\Controller\\Admin\\AdminController::viewLots' => ['privates', '.service_locator.6ABpdEn', 'get_ServiceLocator_6ABpdEnService', true],
            'App\\Controller\\Admin\\AdminController::viewPhotos' => ['privates', '.service_locator.NQFJRwO', 'get_ServiceLocator_NQFJRwOService', true],
            'App\\Controller\\Admin\\SettingsController::dav_change_configuration' => ['privates', '.service_locator.QSiPVOk', 'get_ServiceLocator_QSiPVOkService', true],
            'App\\Controller\\Admin\\SettingsController::delete_box' => ['privates', '.service_locator.hiuod1Z', 'get_ServiceLocator_Hiuod1ZService', true],
            'App\\Controller\\Admin\\SettingsController::delete_email' => ['privates', '.service_locator.yl9MWu0', 'get_ServiceLocator_Yl9MWu0Service', true],
            'App\\Controller\\Admin\\SettingsController::modify_box' => ['privates', '.service_locator.hiuod1Z', 'get_ServiceLocator_Hiuod1ZService', true],
            'App\\Controller\\Admin\\SettingsController::modify_email' => ['privates', '.service_locator.yl9MWu0', 'get_ServiceLocator_Yl9MWu0Service', true],
            'App\\Controller\\Admin\\SettingsController::settings' => ['privates', '.service_locator.vqwTAD6', 'get_ServiceLocator_VqwTAD6Service', true],
            'App\\Controller\\BoothController::upload' => ['privates', '.service_locator.bndMRO9', 'get_ServiceLocator_BndMRO9Service', true],
            'App\\Controller\\MainController::user_settings' => ['privates', '.service_locator.CL11y5L', 'get_ServiceLocator_CL11y5LService', true],
            'App\\Controller\\MainController::verifyLotExist' => ['privates', '.service_locator.vd5gBDM', 'get_ServiceLocator_Vd5gBDMService', true],
            'App\\Controller\\RegistrationController::delete' => ['privates', '.service_locator.Kntl2lG', 'get_ServiceLocator_Kntl2lGService', true],
            'App\\Controller\\RegistrationController::modify' => ['privates', '.service_locator.Kntl2lG', 'get_ServiceLocator_Kntl2lGService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.jlFJwvJ', 'get_ServiceLocator_JlFJwvJService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\Admin\\AdminController:deletePhoto' => ['privates', '.service_locator.NQFJRwO', 'get_ServiceLocator_NQFJRwOService', true],
            'App\\Controller\\Admin\\AdminController:getCsv' => ['privates', '.service_locator.n45nOfE', 'get_ServiceLocator_N45nOfEService', true],
            'App\\Controller\\Admin\\AdminController:mailCsv' => ['privates', '.service_locator.6M8Db7T', 'get_ServiceLocator_6M8Db7TService', true],
            'App\\Controller\\Admin\\AdminController:markAsDone' => ['privates', '.service_locator.9jx6pm9', 'get_ServiceLocator_9jx6pm9Service', true],
            'App\\Controller\\Admin\\AdminController:polist' => ['privates', '.service_locator.1AXQdDL', 'get_ServiceLocator_1AXQdDLService', true],
            'App\\Controller\\Admin\\AdminController:viewLots' => ['privates', '.service_locator.6ABpdEn', 'get_ServiceLocator_6ABpdEnService', true],
            'App\\Controller\\Admin\\AdminController:viewPhotos' => ['privates', '.service_locator.NQFJRwO', 'get_ServiceLocator_NQFJRwOService', true],
            'App\\Controller\\Admin\\SettingsController:dav_change_configuration' => ['privates', '.service_locator.QSiPVOk', 'get_ServiceLocator_QSiPVOkService', true],
            'App\\Controller\\Admin\\SettingsController:delete_box' => ['privates', '.service_locator.hiuod1Z', 'get_ServiceLocator_Hiuod1ZService', true],
            'App\\Controller\\Admin\\SettingsController:delete_email' => ['privates', '.service_locator.yl9MWu0', 'get_ServiceLocator_Yl9MWu0Service', true],
            'App\\Controller\\Admin\\SettingsController:modify_box' => ['privates', '.service_locator.hiuod1Z', 'get_ServiceLocator_Hiuod1ZService', true],
            'App\\Controller\\Admin\\SettingsController:modify_email' => ['privates', '.service_locator.yl9MWu0', 'get_ServiceLocator_Yl9MWu0Service', true],
            'App\\Controller\\Admin\\SettingsController:settings' => ['privates', '.service_locator.vqwTAD6', 'get_ServiceLocator_VqwTAD6Service', true],
            'App\\Controller\\BoothController:upload' => ['privates', '.service_locator.bndMRO9', 'get_ServiceLocator_BndMRO9Service', true],
            'App\\Controller\\MainController:user_settings' => ['privates', '.service_locator.CL11y5L', 'get_ServiceLocator_CL11y5LService', true],
            'App\\Controller\\MainController:verifyLotExist' => ['privates', '.service_locator.vd5gBDM', 'get_ServiceLocator_Vd5gBDMService', true],
            'App\\Controller\\RegistrationController:delete' => ['privates', '.service_locator.Kntl2lG', 'get_ServiceLocator_Kntl2lGService', true],
            'App\\Controller\\RegistrationController:modify' => ['privates', '.service_locator.Kntl2lG', 'get_ServiceLocator_Kntl2lGService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.jlFJwvJ', 'get_ServiceLocator_JlFJwvJService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\Admin\\AdminController::deletePhoto' => '?',
            'App\\Controller\\Admin\\AdminController::getCsv' => '?',
            'App\\Controller\\Admin\\AdminController::mailCsv' => '?',
            'App\\Controller\\Admin\\AdminController::markAsDone' => '?',
            'App\\Controller\\Admin\\AdminController::polist' => '?',
            'App\\Controller\\Admin\\AdminController::viewLots' => '?',
            'App\\Controller\\Admin\\AdminController::viewPhotos' => '?',
            'App\\Controller\\Admin\\SettingsController::dav_change_configuration' => '?',
            'App\\Controller\\Admin\\SettingsController::delete_box' => '?',
            'App\\Controller\\Admin\\SettingsController::delete_email' => '?',
            'App\\Controller\\Admin\\SettingsController::modify_box' => '?',
            'App\\Controller\\Admin\\SettingsController::modify_email' => '?',
            'App\\Controller\\Admin\\SettingsController::settings' => '?',
            'App\\Controller\\BoothController::upload' => '?',
            'App\\Controller\\MainController::user_settings' => '?',
            'App\\Controller\\MainController::verifyLotExist' => '?',
            'App\\Controller\\RegistrationController::delete' => '?',
            'App\\Controller\\RegistrationController::modify' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\AdminController:deletePhoto' => '?',
            'App\\Controller\\Admin\\AdminController:getCsv' => '?',
            'App\\Controller\\Admin\\AdminController:mailCsv' => '?',
            'App\\Controller\\Admin\\AdminController:markAsDone' => '?',
            'App\\Controller\\Admin\\AdminController:polist' => '?',
            'App\\Controller\\Admin\\AdminController:viewLots' => '?',
            'App\\Controller\\Admin\\AdminController:viewPhotos' => '?',
            'App\\Controller\\Admin\\SettingsController:dav_change_configuration' => '?',
            'App\\Controller\\Admin\\SettingsController:delete_box' => '?',
            'App\\Controller\\Admin\\SettingsController:delete_email' => '?',
            'App\\Controller\\Admin\\SettingsController:modify_box' => '?',
            'App\\Controller\\Admin\\SettingsController:modify_email' => '?',
            'App\\Controller\\Admin\\SettingsController:settings' => '?',
            'App\\Controller\\BoothController:upload' => '?',
            'App\\Controller\\MainController:user_settings' => '?',
            'App\\Controller\\MainController:verifyLotExist' => '?',
            'App\\Controller\\RegistrationController:delete' => '?',
            'App\\Controller\\RegistrationController:modify' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
