<?php

namespace Container1bgR63l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vd5gBDMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vd5gBDM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vd5gBDM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'LotRepo' => ['privates', 'App\\Repository\\LotRepository', 'getLotRepositoryService', true],
            'helper' => ['privates', 'App\\Services\\DataBaseHelper', 'getDataBaseHelperService', true],
        ], [
            'LotRepo' => 'App\\Repository\\LotRepository',
            'helper' => 'App\\Services\\DataBaseHelper',
        ]);
    }
}
