<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZvMUppj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZvMUppj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZvMUppj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZvMUppj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZvMUppj\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZvMUppj',
    'container.build_id' => '513d8c05',
    'container.build_time' => 1616513594,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZvMUppj');
