<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOIi4zyU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOIi4zyU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOIi4zyU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOIi4zyU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOIi4zyU\App_KernelDevDebugContainer([
    'container.build_hash' => 'OIi4zyU',
    'container.build_id' => '3bb6a560',
    'container.build_time' => 1616204647,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOIi4zyU');
